# Generated by Django 5.0.3 on 2024-05-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_petadd_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='petadd',
            name='breed',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
