# Generated by Django 5.0.3 on 2024-12-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_userprofile_bio_and_more'),
        ('app1', '0004_petadd_breed'),
    ]

    operations = [
    ]
